// src/themes.js
//
// Each theme controls the app's palette, fonts, and floating decorative
// stickers. Themes are independent of frames.js — a theme changes the
// booth's look and feel, a frame is a transparent PNG overlay on the photo
// itself. Users can mix any theme with any frame.

export const THEMES = {
  girlish: {
    label: "Girlish",
    bg: "linear-gradient(160deg, #ffeaf2 0%, #ffe1ec 45%, #fdeafd 100%)",
    ink: "#2a1c24",
    cream: "#fff8fb",
    accent: "#ff6fa5",
    accentSoft: "#ffd6e7",
    text: "#5b3a52",
    subtext: "#b3688f",
    headline: "#c2447a",
    headlineFont: "'Baloo 2', sans-serif",
    bodyFont: "'Quicksand', sans-serif",
    stickers: ["🎀", "💗", "✨"],
  },
  forest: {
    label: "Forest Fairy",
    bg: "linear-gradient(160deg, #eef7e6 0%, #d9ecc4 45%, #f4f0d8 100%)",
    ink: "#22301c",
    cream: "#f8fbef",
    accent: "#5a8f4f",
    accentSoft: "#cfe8b8",
    text: "#3a4a2e",
    subtext: "#6d8a5c",
    headline: "#3f6b34",
    headlineFont: "'Grand Hotel', cursive",
    bodyFont: "'Nunito', sans-serif",
    stickers: ["🍃", "🦋", "🌿"],
  },
  vintage: {
    label: "Vintage",
    bg: "radial-gradient(ellipse at 50% 30%, #f1e2bd 0%, #ddc48c 55%, #b3925e 100%)",
    ink: "#241a0f",
    cream: "#f6ecd3",
    accent: "#8a5a2f",
    accentSoft: "#d8bd8c",
    text: "#4a3520",
    subtext: "#8a6a42",
    headline: "#5c3b1e",
    headlineFont: "'Playfair Display', serif",
    bodyFont: "'Special Elite', 'Courier New', monospace",
    stickers: ["📷", "✦", "🕰️"],
    grain: true,
  },
  anime: {
    label: "Anime",
    bg: "linear-gradient(160deg, #eef1ff 0%, #ffe0f2 45%, #e0faff 100%)",
    ink: "#1a1030",
    cream: "#fff5fb",
    accent: "#ff2d95",
    accentSoft: "#ffc2e6",
    text: "#241b45",
    subtext: "#7d6aa8",
    headline: "#7c3aed",
    headlineFont: "'Titan One', cursive",
    bodyFont: "'Varela Round', sans-serif",
    stickers: ["⚡", "✨", "🌸", "💥"],
  },
  sea: {
    label: "Sea",
    bg: "linear-gradient(160deg, #e0f7fa 0%, #b2ebf2 45%, #fff8e1 100%)",
    ink: "#062b33",
    cream: "#f0fdff",
    accent: "#0288d1",
    accentSoft: "#b3e5f5",
    text: "#08414f",
    subtext: "#3f7d8c",
    headline: "#01579b",
    headlineFont: "'Pacifico', cursive",
    bodyFont: "'Comfortaa', sans-serif",
    stickers: ["🐚", "🌊", "⭐"],
  },
  heaven: {
    label: "Heaven",
    bg: "linear-gradient(160deg, #fffdf7 0%, #f3e8ff 45%, #fff8e7 100%)",
    ink: "#3a3448",
    cream: "#fffefa",
    accent: "#b39ddb",
    accentSoft: "#e8ddf7",
    text: "#4a4458",
    subtext: "#8a7fa0",
    headline: "#7c6a9c",
    headlineFont: "'Cormorant Garamond', serif",
    bodyFont: "'Josefin Sans', sans-serif",
    stickers: ["☁️", "✨", "🕊️"],
  },
};

export const THEME_ORDER = ["girlish", "forest", "vintage", "anime", "sea", "heaven"];